### ISSUE TITLE
Create calendar grid

### ISSUE THREAD

**Issue by forrestswork** [foshiro/angular-storybook#1]
We will need a calendar grid component. This should be a standalone component called `calendar-grid`.

You will get an array of events that follow this interface:

```typescript
id: number;
type: string; // instructor | evaluator | FTI | Draft
title: string;
description: string;
startDate: string; // UTC date
endDate: string; // UTC date
```

- [ ] create a grid with 7 columns (week view)
- [ ] render the events using buttons
- [ ] these events need to be able to span multiple dates
- [ ] you need to add a class to each event based on the type, like `event-instructor`
- [ ] set the color of the button in css based on the `event-?` class

Instructors are light blue
Evaluator are light green
FTI is light red
Draft is white 

Please use Angular material color functions and css for this.

```css
@use '@angular/material' as mat;
.event-pilot{
  background: mat.get-color-from-palette(mat.$blue-palette, 300);
}
```
